version: '3.8'

services:
  transaction-service:
    build:
      context: ./TransactionService
    container_name: transaction-service
    environment:
      - SERVICE_NAME=transaction-service
      - PORT=3000
    ports:
      - "3001:3000"  
    env_file:
      - ./TransactionService/.env
    depends_on:
      - rabbitmq

  operation-service:
    build:
      context: ./OperationService
    container_name: operation-service
    environment:
      - SERVICE_NAME=operation-service
      - PORT=3000
    ports:
      - "3002:3000"
    env_file:
      - ./OperationService/.env
    depends_on:
      - rabbitmq

  user-service:
    build:
      context: ./UserService
    container_name: user-service
    environment:
      - SERVICE_NAME=user-service
      - PORT=3000
    ports:
      - "3003:3000"
    env_file:
      - ./UserService/.env

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
